### PR TITLE
test: use node test runner

### PR DESCRIPTION
**Pull request by AugustinMauroy**
Just remove jest form devdep and use node 😄

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
it's work on local :

Capture d’écran 2024-06-21 à 11 47 04

**Comment by UlisesGascon** [comment]
Thanks for doing this, @AugustinMauroy!

I think there might be a typo in the pipeline. Could you create a separate PR just for [this commit](https://github.com/nodejs/nodejs-news-feeder/pull/90/commits/006496ab2292402a8f6f9fb7ffdb0ed1080d3bd2)? It seems the CI might not be passing with Jest due to this issue. 🤔

**Comment by UlisesGascon** [comment]
mmm... I was checking the errors in the pipeline. Maybe the issue is related to the timezone and we can solve it by adding an specific timezone with the `TZ` environmental variable https://stackoverflow.com/a/9849524 in the npm script :thinking:

Screenshot from 2024-06-22 13-40-41

Feel free to include https://github.com/nodejs/nodejs-news-feeder/pull/90/commits/006496ab2292402a8f6f9fb7ffdb0ed1080d3bd2 as anyway the tests with Jest seems to be failing in the CI based on https://github.com/nodejs/nodejs-news-feeder/pull/92

**Comment by UlisesGascon** [comment]
Seems like #92 also solved the issue with the tests in this case, so I merged the changes in this branch.

**Review by UlisesGascon — APPROVED** [review]
This is ready now! Great work @AugustinMauroy! :partying_face:

**Pull request merged**
