### PR TITLE
fix: workflow

### PR DESCRIPTION
**Pull request by AugustinMauroy**

### CODE REVIEW

**Comment by AugustinMauroy** [comment]
I hate jest I can't reproduce this issue on my machine

**Comment by UlisesGascon** [comment]
Same! test are passing locally with 18.x and 22.x but not in the CI. Seems like the issue might be related to the timezone https://github.com/nodejs/nodejs-news-feeder/pull/90#issuecomment-2184003593

**Comment by AugustinMauroy** [comment]
YEAH it's green ! I didn't know that changing time zones with node was a good thing.

**Comment by UlisesGascon** [comment]
> YEAH it's green ! I didn't know that changing time zones with node was a good thing.

As I used hardcoded dates for the tests, the machine was not able to replicate the same results if the machine is setup in different timezone. The GitHub action runner probably will be located in the US and I created the tests using Madrid timezone :).

If you want to refactor this further, you can always add `process.env.TZ='Europe/Amsterdam'` directly in the `__tests__/utils.test.js` ([line ref](https://github.com/nodejs/nodejs-news-feeder/blob/main/__tests__/utils.test.js#L4)).

**Review by UlisesGascon — APPROVED** [review]

**Pull request merged**
